@host = http://localhost:4010/api/v1

# @name login
POST {{host}}/users/authLogin HTTP/1.1
Content-Type: application/json

{
   "email": "arihant.saxena@openplaytech.com"
}

###

@verifyToken =fc14de9c51ae18dbb1cf246e2cbae5a1982c14449e6ba459e2db6f02b797ca58

# @name verify
POST {{host}}/users/authVerify/{{verifyToken}} HTTP/1.1

###

# @name isLoggedIn
GET {{host}}/users/isLoggedIn HTTP/1.1

###

# @name logout
POST {{host}}/users/logout HTTP/1.1